import { createClient } from '@/lib/supabase/server';
import { isRequestOriginAllowed } from '@/lib/request-origin';
import { consumeRateLimit } from '@/lib/rate-limit';
const fail=(error:string,status=400)=>Response.json({error},{status});
const limited=(userId:string)=>{const rate=consumeRateLimit(`team-mutation:${userId}`,30,10*60*1000);return rate.allowed?null:Response.json({error:'Muitas alterações em pouco tempo. Aguarde e tente novamente.'},{status:429,headers:{'Retry-After':String(rate.retryAfterSeconds)}})};
async function auth(){const s=await createClient(),{data:{user}}=await s.auth.getUser();return user?{s,user}:null}
export async function GET(req:Request){const ctx=await auth();if(!ctx)return fail('Entre na sua conta para continuar.',401);const id=new URL(req.url).searchParams.get('companyId')||'';const {data,error}=await ctx.s.rpc('team_catalog',{p_company_id:id});if(error)return fail('Não foi possível carregar a equipe.',error.code==='42501'?403:500);return Response.json({members:data||[]});}
export async function PATCH(req:Request){if(!isRequestOriginAllowed(req.headers.get('origin'),req.url,process.env.RAILWAY_PUBLIC_DOMAIN))return fail('Origem não permitida.',403);const ctx=await auth();if(!ctx)return fail('Sessão expirada.',401);const rateResponse=limited(ctx.user.id);if(rateResponse)return rateResponse;const b=await req.json();const {error}=await ctx.s.rpc('team_set_role',{p_company_id:b.companyId,p_user_id:b.userId,p_role:b.role});if(error)return fail(error.code==='42501'?error.message:'Não foi possível alterar a função.',error.code==='42501'?403:400);return Response.json({ok:true});}
export async function DELETE(req:Request){if(!isRequestOriginAllowed(req.headers.get('origin'),req.url,process.env.RAILWAY_PUBLIC_DOMAIN))return fail('Origem não permitida.',403);const ctx=await auth();if(!ctx)return fail('Sessão expirada.',401);const rateResponse=limited(ctx.user.id);if(rateResponse)return rateResponse;const b=await req.json();const {error}=await ctx.s.rpc('team_remove_member',{p_company_id:b.companyId,p_user_id:b.userId});if(error)return fail(error.code==='42501'?error.message:'Não foi possível remover o funcionário.',error.code==='42501'?403:400);return Response.json({ok:true});}
