'use client';
import {useCallback,useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/browser';
type Member={user_id:string;email:string;display_name:string;role:'owner'|'manager'|'member';created_at:string};
export default function Team({companyId,canManage}:{companyId:string;canManage:boolean}){
 const [members,setMembers]=useState<Member[]>([]),[email,setEmail]=useState(''),[name,setName]=useState(''),[role,setRole]=useState<'manager'|'member'>('member'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{const r=await fetch(`/api/team?companyId=${encodeURIComponent(companyId)}`);const j=await r.json();if(r.ok)setMembers(j.members||[]);else setMessage(j.error||'Não foi possível carregar a equipe.');},[companyId]);
 useEffect(()=>{void load()},[load]);
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await createClient().functions.invoke('team-access',{body:{companyId,email,displayName:name,role}});if(r.error||!r.data?.ok)throw new Error(r.data?.error||'Não foi possível adicionar o funcionário.');setEmail('');setName('');setMessage('Funcionário adicionado. Ele receberá o convite de acesso.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível adicionar o funcionário.');}finally{setBusy(false)}}
 async function update(member:Member,next:string){setBusy(true);setMessage('');try{const r=await fetch('/api/team',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,userId:member.user_id,role:next})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível alterar a função.');}finally{setBusy(false)}}
 async function remove(member:Member){if(!window.confirm(`Remover ${member.display_name} da equipe?`))return;setBusy(true);setMessage('');try{const r=await fetch('/api/team',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,userId:member.user_id})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível remover o funcionário.');}finally{setBusy(false)}}
 return <section className="team-panel"><div className="section-head"><div><span className="eyebrow">EQUIPE</span><h2>Quem atende seus clientes</h2></div><span className="team-limit">{Math.max(0,members.length-1)}/3 funcionários</span></div><p className="team-intro">Adicione até três funcionários, defina a função e acompanhe quem ficou responsável por cada oportunidade.</p>{canManage&&<form className="team-form" onSubmit={add}><label>Nome<input required minLength={2} value={name} onChange={e=>setName(e.target.value)} placeholder="João da Silva"/></label><label>E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="joao@empresa.com"/></label><label>Função<select value={role} onChange={e=>setRole(e.target.value as 'manager'|'member')}><option value="member">Funcionário</option><option value="manager">Gestor</option></select></label><button className="primary" disabled={busy||members.length>=4}>Adicionar funcionário</button></form>}{!canManage&&<p className="team-readonly">Somente o administrador da empresa pode alterar a equipe.</p>}<div className="team-list">{members.map(m=><article className="team-member" key={m.user_id}><span className="owner-avatar">{m.display_name.slice(0,1).toUpperCase()}</span><div><strong>{m.display_name}</strong><small>{m.email}</small></div><span className={`team-role ${m.role}`}>{m.role==='owner'?'Administrador':m.role==='manager'?'Gestor':'Funcionário'}</span>{canManage&&m.role!=='owner'&&<><select aria-label={`Função de ${m.display_name}`} disabled={busy} value={m.role} onChange={e=>void update(m,e.target.value)}><option value="member">Funcionário</option><option value="manager">Gestor</option></select><button className="text-button" disabled={busy} onClick={()=>void remove(m)}>Remover</button></>}</article>)}</div>{message&&<p role="status" className="team-message">{message}</p>}</section>;
}
