export const templates = {
 generic: { label:'Geral', noun:'Oportunidade', stages:['Novo','Em análise','Proposta','Em negociação','Aguardando decisão','Fechado','Perdido'], titles:['Pedido de orçamento','Nova proposta','Consulta inicial','Revisão de proposta','Solicitação comercial'], field:'Serviço' },
 events: { label:'Eventos', noun:'Evento', stages:['Novo contato','Briefing','Proposta','Ajustes','Aguardando sinal','Confirmado','Perdido'], titles:['Casamento · 120 convidados','Evento corporativo · 80 pessoas','Aniversário · 50 convidados','Formatura · recepção','Celebração familiar'], field:'Tipo e data do evento' },
 real_estate: { label:'Imobiliário', noun:'Atendimento', stages:['Novo interessado','Atendimento','Visita agendada','Visita realizada','Proposta','Negociação','Decisão','Fechado','Perdido'], titles:['Apartamento · Pituba','Casa · Vilas do Atlântico','Sala comercial · Salvador','Apartamento · Rio Vermelho','Casa · Camaçari'], field:'Imóvel e visita' },
 hvac: { label:'Climatização', noun:'Orçamento', stages:['Contato','Avaliação','Visita técnica','Orçamento','Ajustes','Aprovação','Execução','Perdido'], titles:['Instalação de ar-condicionado','Manutenção de climatização','Projeto de refrigeração','Troca de equipamento','Visita técnica'], field:'Equipamento e local' },
 marble: { label:'Marmoraria', noun:'Projeto', stages:['Contato','Orçamento','Medição','Projeto / alteração','Aprovação','Produção / instalação','Perdido'], titles:['Bancada de cozinha','Lavatório sob medida','Escada em granito','Ilha de cozinha','Revestimento de banheiro'], field:'Material e medição' },
 construction: { label:'Reformas', noun:'Obra', stages:['Contato','Levantamento','Visita','Orçamento','Ajustes','Contrato','Em execução','Perdido'], titles:['Reforma de apartamento','Ampliação residencial','Reforma comercial','Projeto estrutural','Adequação de escritório'], field:'Endereço e escopo' },
 furniture: { label:'Móveis planejados', noun:'Projeto', stages:['Contato','Briefing','Medição','Projeto','Proposta','Ajustes','Contrato','Perdido'], titles:['Cozinha planejada','Armários para quarto','Home office','Painel de sala','Closet sob medida'], field:'Ambiente e medição' },
 dental: { label:'Odontologia', noun:'Plano de tratamento', stages:['Contato','Avaliação','Plano apresentado','Dúvidas','Aguardando decisão','Agendado','Perdido'], titles:['Avaliação ortodôntica','Implante dentário','Clareamento','Tratamento preventivo','Prótese dentária'], field:'Tratamento' },
 aesthetics: { label:'Estética', noun:'Atendimento', stages:['Contato','Avaliação','Plano apresentado','Dúvidas','Aguardando decisão','Agendado','Perdido'], titles:['Avaliação facial','Procedimento corporal','Plano de sessões','Tratamento de pele','Consulta estética'], field:'Procedimento' },
 pools: { label:'Piscinas', noun:'Projeto', stages:['Contato','Visita','Orçamento','Projeto','Ajustes','Aprovação','Instalação','Perdido'], titles:['Piscina residencial','Reforma de piscina','Sistema de filtragem','Piscina em condomínio','Manutenção programada'], field:'Local e dimensões' },
 equipment_rental: { label:'Locação de equipamentos', noun:'Locação', stages:['Contato','Disponibilidade','Cotação','Negociação','Reserva','Contrato','Entregue','Perdido'], titles:['Locação de plataforma','Aluguel de gerador','Locação de andaimes','Equipamento para obra','Máquina para terraplenagem'], field:'Equipamento e período' },
 glass_aluminum: { label:'Esquadrias e vidraçarias', noun:'Projeto', stages:['Contato','Medição','Orçamento','Projeto','Ajustes','Aprovação','Instalação','Perdido'], titles:['Porta de vidro','Box sob medida','Esquadrias de alumínio','Fachada envidraçada','Janela sob medida'], field:'Medidas e material' },
} as const;
export type TemplateKey = keyof typeof templates;
export const stageKind=(template:TemplateKey,index:number):'open'|'won'|'lost'=>index===templates[template].stages.length-1?'lost':index===templates[template].stages.length-2?'won':'open';
export const actionTypes=['Ligar','WhatsApp','Enviar proposta','Confirmar','Cobrar retorno','Reunião','Visita','Personalizado'] as const;
export const demoNames=['Mariana Souza','Carlos Almeida','Empresa Horizonte','Fernanda Lima','Renato Oliveira','Paula Santos','Grupo Aurora','Juliana Costa','Ricardo Mendes','Ateliê Sol','Patrícia Rocha','Bruno Carvalho','Camila Nunes','Eduardo Lima','Condomínio Jardim','Ana Beatriz'];
