import Link from "next/link";
import { ArrowRight, Check, ShieldCheck, Target, Users, BarChart3, MessageCircle, Package } from "lucide-react";
import { AetherMark } from "../../aether-logo";
import { trialWhatsAppUrl } from "../../landing-cta";

type Kind = "como-funciona" | "recursos" | "para-quem";
const content = {
  "como-funciona": { eyebrow: "COMO FUNCIONA", title: "Do primeiro contato ao próximo passo, sem perder o ritmo.", intro: "Uma operação clara em três movimentos: registrar, priorizar e agir.", cards: [[Target,"1. Registre o contexto","Nome, telefone, oportunidade, valor e responsável ficam juntos desde o primeiro contato."],[MessageCircle,"2. Priorize o retorno","O radar coloca vencidos, compromissos de hoje e conversas sem próximo passo na ordem certa."],[Check,"3. Conclua e aprenda","Cada ação atualiza o histórico e as métricas para a equipe saber o que funciona."]] },
  "recursos": { eyebrow: "RECURSOS", title: "Tudo que a equipe precisa para agir no momento certo.", intro: "O Aether Flow conecta CRM, mensagens e operação em um ambiente simples.", cards: [[BarChart3,"Métricas que orientam","Ganhos, perdas, taxa de ganho, valor em aberto e resumo semanal em uma leitura."],[Users,"Equipe com responsabilidade","Adicione até três funcionários, defina a função e saiba quem ficou responsável por cada contato."],[Package,"Operação conectada","Produtos, validade, pedidos, avarias e alertas ligados ao dia a dia da empresa."]] },
  "para-quem": { eyebrow: "PARA QUEM É", title: "Para empresas que não podem deixar uma conversa esfriar.", intro: "Salões, oficinas, clínicas, consultorias e times comerciais trabalham com a mesma clareza.", cards: [[Users,"Times pequenos","Cada pessoa sabe a próxima ação e o gestor acompanha sem cobrar no escuro."],[Target,"Serviços com retorno","Orçamentos, agendamentos e propostas ficam em uma fila de atenção."],[ShieldCheck,"Dados separados","Cada empresa tem seu ambiente, histórico e permissões próprios."]] }
} as const;

export default function LandingSubpage({ kind }: { kind: Kind }) {
 const item = content[kind];
 return <main className="landing-subpage"><header className="landing-subnav"><Link href="/landing" className="landing-brand"><AetherMark/><span><strong>Aether Flow</strong><small>RADAR DE OPORTUNIDADES</small></span></Link><Link className="landing-subnav-back" href="/landing">Voltar para a landing</Link></header><section className="landing-subhero"><span className="landing-eyebrow">{item.eyebrow}</span><h1>{item.title}</h1><p>{item.intro}</p><div className="landing-actions"><a className="landing-primary" href={trialWhatsAppUrl} target="_blank" rel="noreferrer">Teste grátis por 7 dias <ArrowRight size={17}/></a><Link className="landing-secondary" href="/login">Entrar</Link></div></section><section className="landing-subgrid">{item.cards.map(([Icon,title,text]) => <article key={title}><span className="feature-icon blue"><Icon size={22}/></span><h2>{title}</h2><p>{text}</p></article>)}</section><section className="landing-subproof"><ShieldCheck size={18}/><span>Ambiente separado por empresa, com histórico e permissões para cada integrante.</span></section><footer className="landing-subfooter"><Link href="/landing/como-funciona">Como funciona</Link><Link href="/landing/recursos">Recursos</Link><Link href="/landing/para-quem">Para quem é</Link><Link href="/termos">Termos</Link></footer></main>;
}
