import Link from "next/link";
import { ArrowRight, Check, ShieldCheck, Target, Users, BarChart3, MessageCircle, Package, Image as ImageIcon, WalletCards, CircleHelp } from "lucide-react";
import { AetherMark } from "../../aether-logo";
import { trialWhatsAppUrl } from "../../landing-cta";
import LandingProductGallery from "../../landing-product-gallery";

type Kind = "como-funciona" | "recursos" | "para-quem" | "telas" | "preco" | "duvidas";
const content = {
  "como-funciona": { eyebrow: "COMO FUNCIONA", title: "Do primeiro contato ao próximo passo, sem perder o ritmo.", intro: "Uma operação clara em três movimentos: registrar, priorizar e agir.", cards: [[Target,"1. Registre o contexto","Nome, telefone, oportunidade, valor e responsável ficam juntos desde o primeiro contato."],[MessageCircle,"2. Priorize o retorno","O radar coloca vencidos, compromissos de hoje e conversas sem próximo passo na ordem certa."],[Check,"3. Conclua e aprenda","Cada ação atualiza o histórico e as métricas para a equipe saber o que funciona."]] },
  "recursos": { eyebrow: "RECURSOS", title: "Tudo que a equipe precisa para agir no momento certo.", intro: "O Aether Flow conecta CRM, mensagens e operação em um ambiente simples.", cards: [[BarChart3,"Métricas que orientam","Ganhos, perdas, taxa de ganho, valor em aberto e resumo semanal em uma leitura."],[Users,"Equipe com responsabilidade","Adicione até três funcionários, defina a função e saiba quem ficou responsável por cada contato."],[Package,"Operação conectada","Produtos, validade, pedidos, avarias e alertas ligados ao dia a dia da empresa."]] },
  "para-quem": { eyebrow: "PARA QUEM É", title: "Para empresas que não podem deixar uma conversa esfriar.", intro: "Salões, oficinas, clínicas, consultorias e times comerciais trabalham com a mesma clareza.", cards: [[Users,"Times pequenos","Cada pessoa sabe a próxima ação e o gestor acompanha sem cobrar no escuro."],[Target,"Serviços com retorno","Orçamentos, agendamentos e propostas ficam em uma fila de atenção."],[ShieldCheck,"Dados separados","Cada empresa tem seu ambiente, histórico e permissões próprios."]] }
  ,"telas": { eyebrow: "TELAS REAIS", title: "Veja o Aether Flow trabalhando com dados de demonstração.", intro: "Painel, radar, contatos e operação aparecem no mesmo contexto para você entender o fluxo antes de começar.", cards: [[ImageIcon,"Painel de atenção","Prioridades, valor em aberto e próximos passos ficam visíveis em uma leitura."],[MessageCircle,"Preparar contato","O contexto da negociação vem antes da mensagem pronta para o WhatsApp."],[Package,"Operação conectada","Catálogo, disponibilidade e movimentações ficam ligados à oportunidade."]] }
  ,"preco": { eyebrow: "PLANO", title: "Comece com sete dias grátis e cancele quando quiser.", intro: "Um ambiente por empresa, equipe enxuta e os recursos essenciais para acompanhar vendas sem planilhas espalhadas.", cards: [[WalletCards,"Plano claro","R$ 67 por mês após o período de teste, sem multa de cancelamento."],[Users,"Até três funcionários","O administrador adiciona a equipe e define quem acompanha cada oportunidade."],[ShieldCheck,"Dados protegidos","Isolamento por empresa, permissões e histórico das ações da equipe."]] }
  ,"duvidas": { eyebrow: "DÚVIDAS", title: "Comece sem complicar a rotina da equipe.", intro: "As respostas essenciais para avaliar o Aether Flow com segurança e contexto.", cards: [[CircleHelp,"Preciso cadastrar tudo de uma vez?","Não. Você pode começar com uma oportunidade e adicionar contatos conforme a rotina avança."],[MessageCircle,"O WhatsApp envia sozinho?","Você revisa a mensagem antes de abrir o WhatsApp. O Aether Flow registra o próximo passo."],[ShieldCheck,"Posso cancelar?","Sim. O plano pode ser cancelado quando quiser, sem multa, conforme as condições apresentadas no checkout."]] }
} as const;

export default function LandingSubpage({ kind }: { kind: Kind }) {
 const item = content[kind];
 return <main className="landing-subpage"><header className="landing-subnav"><Link href="/landing" className="landing-brand"><AetherMark/><span><strong>Aether Flow</strong><small>RADAR DE OPORTUNIDADES</small></span></Link><Link className="landing-subnav-back" href="/landing">Voltar para a landing</Link></header><section className="landing-subhero"><span className="landing-eyebrow">{item.eyebrow}</span><h1>{item.title}</h1><p>{item.intro}</p><div className="landing-actions"><a className="landing-primary" href={trialWhatsAppUrl} target="_blank" rel="noreferrer">Teste grátis por 7 dias <ArrowRight size={17}/></a><Link className="landing-secondary" href="/login">Entrar</Link></div></section><section className="landing-subgrid">{item.cards.map(([Icon,title,text]) => <article key={title}><span className="feature-icon blue"><Icon size={22}/></span><h2>{title}</h2><p>{text}</p></article>)}</section>{kind === "telas" && <section className="landing-sub-gallery"><LandingProductGallery/></section>}<section className="landing-subproof"><ShieldCheck size={18}/><span>Ambiente separado por empresa, com histórico e permissões para cada integrante.</span></section><footer className="landing-subfooter"><Link href="/landing/como-funciona">Como funciona</Link><Link href="/landing/telas">Telas reais</Link><Link href="/landing/recursos">Recursos</Link><Link href="/landing/para-quem">Para quem é</Link><Link href="/landing/preco">Preço</Link><Link href="/landing/duvidas">Dúvidas</Link><Link href="/termos">Termos</Link></footer></main>;
}
