"use client";
import { useEffect, useState } from "react";
type Item={id:string;name:string;body:string};
const defaults:Item[]=[{id:"follow-up",name:"Acompanhamento",body:"Olá, {nome}. Estou entrando em contato para dar continuidade à nossa conversa sobre {oportunidade}."},{id:"proposal",name:"Proposta",body:"Olá, {nome}. Podemos conversar sobre a proposta de {oportunidade}?"}];
export default function MessagesPage(){
 const [company,setCompany]=useState<{id:string;name:string}|null>(null),[items,setItems]=useState<Item[]>(defaults),[name,setName]=useState(""),[body,setBody]=useState("");
 useEffect(()=>{fetch("/api/workspace").then(r=>r.json()).then(async d=>{if(!d.company)return;setCompany(d.company);const r=await fetch(`/api/message-templates?companyId=${d.company.id}`);if(r.ok){const x=await r.json();if(x.items?.length)setItems(x.items);}}).catch(()=>{});},[]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();if(!company||!name.trim()||!body.trim())return;const r=await fetch("/api/message-templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId:company.id,name,body})});if(r.ok){const x=await r.json();setItems([...items,x.item]);setName("");setBody("");}};
 const remove=async(id:string)=>{if(!company)return;await fetch(`/api/message-templates?companyId=${company.id}&id=${id}`,{method:"DELETE"});setItems(items.filter(i=>i.id!==id));};
 return <main className="page-body message-bank-page"><div className="heading"><div><div className="eyebrow">BIBLIOTECA</div><h1>Mensagens prontas</h1><p>Crie modelos e escolha um deles ao abrir o WhatsApp.</p></div></div><section className="message-bank-grid"><div className="message-bank-list">{items.map(x=><article key={x.id}><strong>{x.name}</strong><p>{x.body}</p>{!defaults.some(d=>d.id===x.id)&&<button className="text-button" onClick={()=>void remove(x.id)}>Excluir</button>}</article>)}</div><form className="message-bank-form" onSubmit={add}><h2>Nova mensagem</h2><input aria-label="Nome da mensagem" placeholder="Nome da mensagem" value={name} onChange={e=>setName(e.target.value)} maxLength={80}/><textarea aria-label="Texto da mensagem" placeholder="Use {nome} e {oportunidade}" value={body} onChange={e=>setBody(e.target.value)} maxLength={1000} rows={6}/><button className="primary" disabled={!name.trim()||!body.trim()||!company}>Salvar modelo</button></form></section></main>;
}
