-- Aether Flow / Aether Works
-- Conhecimento comercial derivado do PDF AETHER_AI_CONHECIMENTO_7_LIVROS_2026-09-28.pdf
-- Gerado a partir da extração completa das 21 páginas do PDF em 2026-10-06.
-- Este arquivo cria um acervo consultável; ele não aplica a migration nem altera produção.
-- O próprio PDF registra limitações de OCR, páginas sem texto e que é uma síntese dos livros.

begin;

create table if not exists public.aether_negotiation_documents (
  document_key text primary key,
  title text not null,
  source_url text not null,
  source_drive_file_id text not null,
  version text,
  published_on date,
  page_count integer not null,
  provenance text not null,
  limitations text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.aether_negotiation_catalog (
  document_key text primary key references public.aether_negotiation_documents(document_key) on delete cascade,
  spreadsheet_id text not null,
  spreadsheet_title text not null,
  sheet_name text not null,
  spreadsheet_updated_at timestamptz,
  resource_title text not null,
  resource_date date,
  scope text not null,
  usage_in_jarvis text not null,
  access_url text not null,
  catalog_provenance text not null
);

create table if not exists public.aether_negotiation_pages (
  document_key text not null references public.aether_negotiation_documents(document_key) on delete cascade,
  page_number integer not null check (page_number > 0),
  body text not null,
  primary key (document_key, page_number)
);

create table if not exists public.aether_negotiation_sources (
  document_key text not null references public.aether_negotiation_documents(document_key) on delete cascade,
  source_key text not null,
  title text not null,
  author text not null,
  extracted_pages text not null,
  limitation text not null,
  primary key (document_key, source_key)
);

create table if not exists public.aether_negotiation_rules (
  document_key text not null references public.aether_negotiation_documents(document_key) on delete cascade,
  rule_key text not null,
  category text not null,
  stage text not null,
  priority integer not null,
  rule_text text not null,
  operational_detail text not null,
  source_basis text not null,
  primary key (document_key, rule_key)
);

create table if not exists public.aether_negotiation_scenarios (
  document_key text not null references public.aether_negotiation_documents(document_key) on delete cascade,
  scenario_key text not null,
  signal text not null,
  recommended_action text not null,
  avoid_action text not null,
  primary key (document_key, scenario_key)
);

insert into public.aether_negotiation_documents (document_key, title, source_url, source_drive_file_id, version, published_on, page_count, provenance, limitations) values ('aether_ai_7_books_2026_09_28', E'Aether AI | Conhecimento dos 7 livros', E'https://drive.google.com/file/d/10RuHgnNFMjxCnb3kXw8PbsPOGFYOul-4/view?usp=drivesdk', '10RuHgnNFMjxCnb3kXw8PbsPOGFYOul-4', '1.0', '2026-09-28', 21, E'PDF de consulta compilado em 28/09/2026 a partir de um sistema operacional de negociação e de um relatório de síntese produzidos em 25/09/2026; localizado na aba Conhecimento dos Livros da planilha universal.', E'O PDF não é o PDF histórico original dos sete livros. O texto informa limitações de extração/OCR, cerca de 1.674 páginas declaradas nos livros, 1.605 páginas/seções com texto extraível e ausência de releitura humana linha a linha de cada parágrafo.') on conflict (document_key) do update set title=excluded.title, source_url=excluded.source_url, source_drive_file_id=excluded.source_drive_file_id, version=excluded.version, published_on=excluded.published_on, page_count=excluded.page_count, provenance=excluded.provenance, limitations=excluded.limitations;
insert into public.aether_negotiation_catalog (document_key, spreadsheet_id, spreadsheet_title, sheet_name, spreadsheet_updated_at, resource_title, resource_date, scope, usage_in_jarvis, access_url, catalog_provenance) values ('aether_ai_7_books_2026_09_28', '1mQ8mS5YMJ4qUfo_yPMCVx8kA-Ul5g1uNVRLB2_MarEI', E'JARVIS CONTROL CENTER - WhatsApp e Vendas', E'Conhecimento dos Livros', '2026-10-05T14:19:46.119Z', E'Conhecimento dos 7 livros (PDF)', '2026-09-28', E'Sistema operacional de negociação e vendas + relatório de síntese de sete livros', E'Referência universal para pesquisa, diagnóstico, WhatsApp, propostas, negociação e follow-up. Aplicar as regras conforme contexto, evidência e estágio.', E'https://drive.google.com/file/d/10RuHgnNFMjxCnb3kXw8PbsPOGFYOul-4/view?usp=drivesdk', E'PDF de consulta compilado em 28/09/2026 a partir de AETHER_AI_NEGOTIATION_OPERATING_SYSTEM.md e AETHER_AI_BOOK_SYNTHESIS_REPORT.md (25/09/2026). O PDF histórico original não foi localizado. A própria planilha registra as limitações de extração e verificação.') on conflict (document_key) do update set spreadsheet_id=excluded.spreadsheet_id, spreadsheet_title=excluded.spreadsheet_title, sheet_name=excluded.sheet_name, spreadsheet_updated_at=excluded.spreadsheet_updated_at, resource_title=excluded.resource_title, resource_date=excluded.resource_date, scope=excluded.scope, usage_in_jarvis=excluded.usage_in_jarvis, access_url=excluded.access_url, catalog_provenance=excluded.catalog_provenance;

insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 1, E'Aether AI | Conhecimento dos 7 livros') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 2, E'Este PDF reúne dois documentos Aether AI produzidos em 25/09/2026 a partir de sete livros: o') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 3, E'AETHER AI — NEGOTIATION & SALES OPERATING SYSTEM') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 4, E'Edição identificável') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 5, E'Edição identificável') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 6, E'1. Verdade, consentimento e limites éticos. Não inventar provas, resultados, clientes,') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 7, E'[REGRA OPERACIONAL]Apresentarpreçojuntocomescopo, resultadospretendidos(semgaranti-') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 8, E'Pesquisar, quando permitido e relevante, site, páginas de agendamento, perfis públicos, listagens') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 9, E'As perguntas precisam caber no contexto. Em prospecção fria, começar com evidência pública') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 10, E'[REGRA OPERACIONAL] Fazer perguntas que realmente aceitem resposta inesperada. Evitar') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 11, E'12. Objeções: protocolo de diagnóstico') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 12, E'13. Preço, proposta e oferta Aether Works') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 13, E'participa e o que será preparado.') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 14, E'Técnica Ativar quando Evitar quando / falha típica') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 15, E'Síntese') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 16, E'opção se o critério for justo e as partes concordarem; de outro modo, descobrir variáveis e critérios') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 17, E'23. Como trabalhar com Murilo') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 18, E'Cenário Ação correta no sistema Falha que o teste impede') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 19, E'Apêndice: relatório de síntese dos livros') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 20, E'Principais contradições e resolução') on conflict (document_key, page_number) do update set body=excluded.body;
insert into public.aether_negotiation_pages (document_key, page_number, body) values ('aether_ai_7_books_2026_09_28', 21, E'6. BATNA, interesses, critérios, variáveis e execução incluídos na preparação de negociação.') on conflict (document_key, page_number) do update set body=excluded.body;

insert into public.aether_negotiation_sources (document_key, source_key, title, author, extracted_pages, limitation) values ('aether_ai_7_books_2026_09_28', E'cialdini', E'As armas da persuasão', E'Robert B. Cialdini', E'59/62', E'Princípios de influência e defesas; três páginas sem texto extraível; exemplos não são automaticamente experimentos.') on conflict (document_key, source_key) do update set title=excluded.title, author=excluded.author, extracted_pages=excluded.extracted_pages, limitation=excluded.limitation;
insert into public.aether_negotiation_sources (document_key, source_key, title, author, extracted_pages, limitation) values ('aether_ai_7_books_2026_09_28', E'challenger', E'A venda desafiadora', E'Matthew Dixon e Brent Adamson', E'234/234', E'Cobertura textual ampla, com ruído de tradução/OCR; alegações do CEB não foram reavaliadas.') on conflict (document_key, source_key) do update set title=excluded.title, author=excluded.author, extracted_pages=excluded.extracted_pages, limitation=excluded.limitation;
insert into public.aether_negotiation_sources (document_key, source_key, title, author, extracted_pages, limitation) values ('aether_ai_7_books_2026_09_28', E'spin', E'Alcançando excelência em vendas: SPIN Selling', E'Neil Rackham', E'207/218', E'Onze páginas sem texto extraível; observações de campo não equivalem a causalidade universal.') on conflict (document_key, source_key) do update set title=excluded.title, author=excluded.author, extracted_pages=excluded.extracted_pages, limitation=excluded.limitation;
insert into public.aether_negotiation_sources (document_key, source_key, title, author, extracted_pages, limitation) values ('aether_ai_7_books_2026_09_28', E'ury', E'Como chegar ao sim com você mesmo', E'William Ury', E'104/112', E'Edição/ano não estabelecidos com segurança; não confundir com o livro coescrito com Fisher.') on conflict (document_key, source_key) do update set title=excluded.title, author=excluded.author, extracted_pages=excluded.extracted_pages, limitation=excluded.limitation;
insert into public.aether_negotiation_sources (document_key, source_key, title, author, extracted_pages, limitation) values ('aether_ai_7_books_2026_09_28', E'carnegie', E'Como fazer amigos e influenciar pessoas', E'Dale Carnegie', E'281/282', E'Conselhos, histórias e casos; filtro ético e contextual necessário.') on conflict (document_key, source_key) do update set title=excluded.title, author=excluded.author, extracted_pages=excluded.extracted_pages, limitation=excluded.limitation;
insert into public.aether_negotiation_sources (document_key, source_key, title, author, extracted_pages, limitation) values ('aether_ai_7_books_2026_09_28', E'kahneman', E'Rápido e devagar: duas formas de pensar', E'Daniel Kahneman', E'459/497', E'Trinta e oito páginas/seções sem texto; não generalizar cada efeito a todos os compradores.') on conflict (document_key, source_key) do update set title=excluded.title, author=excluded.author, extracted_pages=excluded.extracted_pages, limitation=excluded.limitation;
insert into public.aether_negotiation_sources (document_key, source_key, title, author, extracted_pages, limitation) values ('aether_ai_7_books_2026_09_28', E'voss', E'Negocie como se sua vida dependesse disso', E'Chris Voss e Tahl Raz', E'261/269', E'Experiência de negociação de crise; transferência para B2B é parcial e deve ser adaptada.') on conflict (document_key, source_key) do update set title=excluded.title, author=excluded.author, extracted_pages=excluded.extracted_pages, limitation=excluded.limitation;

insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_truth_consent', E'priority', E'all', 1, E'Verdade, consentimento e limites éticos vêm antes de qualquer técnica de influência.', E'Não inventar provas, resultados, clientes, urgência, escassez ou autoridade; não esconder custo ou condição material; não explorar vulnerabilidade.', E'SÍNTESE; regras 3 e 21') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_context_evidence', E'priority', E'all', 2, E'Contexto e evidência vêm antes da interpretação.', E'Separar observação, fala do prospect, hipótese, inferência e dado medido; não diagnosticar por estereótipo.', E'SÍNTESE; seção 3') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_diagnosis_before_solution', E'priority', E'discovery', 3, E'Entender antes de prescrever.', E'Investigar situação, impacto, critérios e prioridade antes de propor uma solução complexa.', E'SPIN + Challenger + seção 3') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_interests_before_positions', E'priority', E'discovery', 4, E'Interesses vêm antes de posições.', E'Descobrir o que a pessoa precisa proteger, mudar ou obter; considerar alternativas sem acordo.', E'Ury + Voss + seção 3') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_autonomy', E'priority', E'all', 5, E'A autonomia do interlocutor prevalece.', E'Ajudar a decidir, dar espaço para recusa e não fabricar pressão ou dívida emocional.', E'Carnegie + Ury + Voss + Cialdini') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_proportionality', E'priority', E'all', 6, E'Usar a intervenção menos intrusiva capaz de avançar a conversa.', E'Ajustar a profundidade ao estágio e ao risco da decisão.', E'INFERÊNCIA operacional') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_execution', E'priority', E'commitment', 7, E'Intenção vaga não é compromisso.', E'Confirmar dono, escopo, prazo, dependências, pagamento e próximo passo.', E'SPIN + Voss + seção 3') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'priority_language_last', E'priority', E'all', 8, E'Escolher linguagem somente depois de objetivo, contexto, fatos e diagnóstico.', E'Não começar por uma mensagem pronta ou por um script rígido.', E'SÍNTESE; seção 1') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'diagnostic_fact_hypothesis_split', E'diagnosis', E'research', 10, E'Separar fatos conhecidos de hipóteses.', E'Registrar empresa, papel, origem, fonte/data, declaração direta, necessidade possível, custo, frustração, urgência e decisão interna sem misturá-los.', E'SÍNTESE; seção 5') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'diagnostic_neutral_question', E'diagnosis', E'discovery', 11, E'Quando a interpretação mudar a estratégia, fazer uma pergunta neutra.', E'Manter hipóteses múltiplas para silêncio, tom ou frases curtas; não alegar leitura certa de emoção ou intenção.', E'Kahneman + seção 4') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'spin_situation', E'discovery', E'discovery', 20, E'Perguntas de situação devem ser poucas e baseadas em pesquisa.', E'Perguntar apenas o que é necessário para entender o processo atual e não repetir informação pública.', E'SPIN; seção 8') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'spin_problem', E'discovery', E'discovery', 21, E'Explorar dificuldade real sem induzir uma resposta.', E'Usar perguntas abertas sobre falha, atraso, retrabalho, risco ou perda reconhecida pelo prospect.', E'SPIN; seção 8') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'spin_implication', E'discovery', E'discovery', 22, E'Só aprofundar implicações quando o problema estiver confirmado.', E'Conectar a dificuldade a impacto operacional, financeiro ou de decisão apenas com base no que foi dito ou medido.', E'SPIN; seção 8') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'spin_need_payoff', E'discovery', E'discovery', 23, E'O prospect deve articular o valor de uma mudança.', E'Perguntar o que melhoraria, quem se beneficiaria e como reconheceriam avanço antes de apresentar a oferta.', E'SPIN; seção 8') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'challenger_reframe_after_relevance', E'teaching', E'discovery', 30, E'Ensinar ou reenquadrar só depois de relevância e evidência.', E'Apresentar um insight curto como hipótese a validar, nunca como diagnóstico definitivo ou aula para mostrar inteligência.', E'Challenger + seção 9') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'voss_label_as_check', E'communication', E'discovery', 40, E'Rótulos e espelhamento servem para checar entendimento, não para simular empatia.', E'Usar formulação breve e permitir correção; um resumo só vale quando a outra parte confirma.', E'Voss + seção 10') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'voss_black_swan', E'negotiation', E'negotiation', 41, E'Procurar informação faltante que mude valor, restrição, autoridade, cronograma ou execução.', E'Investigar com curiosidade proporcional e sem coletar dados pessoais irrelevantes.', E'Voss; seção 11') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'price_scope_transparency', E'offer', E'proposal', 50, E'Preço deve vir com escopo, limites, custos e incertezas.', E'Não apresentar preço pago como retorno garantido; explicitar recorrência, responsabilidade, suporte, propriedade, saída e medida de sucesso disponível.', E'Aether Works; seção 13 e 22') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'no_artificial_anchor', E'negotiation', E'negotiation', 51, E'Âncoras e comparações precisam de base justa.', E'Sem dados de custo, escopo, margem, alternativas e limites, não usar números ímpares ou âncoras para criar aparência de cálculo.', E'Voss + Kahneman; seção 11') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'objection_diagnose', E'objection', E'objection', 60, E'Objeção é sinal para investigar, não desculpa para contornar.', E'Descobrir se o bloqueio é prioridade, orçamento, confiança, risco, autoridade, prazo ou encaixe antes de responder.', E'SÍNTESE; seção 12') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'discount_tradeoff', E'objection', E'negotiation', 61, E'Qualquer concessão exige troca real.', E'Negociar escopo, termo, prazo ou condição com critério; não dar desconto reflexivo nem dividir a diferença automaticamente.', E'Voss + seção 19') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'followup_reason', E'follow_up', E'follow_up', 70, E'Follow-up precisa de motivo legítimo e próximo passo proporcional.', E'Não tratar silêncio como consentimento; depois de tentativa apropriada ou pedido para parar, encerrar e suprimir contato.', E'SÍNTESE; seção 14 e cenários') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'no_pitch_before_need', E'anti_pattern', E'prospecting', 80, E'Não demonstrar o produto ou fazer pitch antes de entender necessidade e obter abertura.', E'Evitar mensagem genérica, bateria de perguntas, funcionalidade sem contexto e fecho precoce.', E'SPIN + Challenger + seção 20') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'refusal_is_valid', E'ethics', E'all', 90, E'Recusa legítima encerra ou redireciona a conversa.', E'Agradecer, aceitar, suprimir contato quando pedido e não transformar não em objeção a vencer.', E'Ury + Voss + seção 21 e 26') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'recommend_not_sell', E'ethics', E'all', 91, E'Recomendar não vender quando faltar encaixe, evidência ou capacidade.', E'Explicar o motivo e orientar sem empurrar serviço.', E'Aether Works; seção 22 e cenário Aether') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;
insert into public.aether_negotiation_rules (document_key, rule_key, category, stage, priority, rule_text, operational_detail, source_basis) values ('aether_ai_7_books_2026_09_28', E'self_audit', E'quality', E'all', 100, E'Auditar cada resposta antes de usar.', E'Reconstituir evidência, procurar hipótese escondida, testar diagnóstico antes da técnica, ética, adequação, economia, leitura provável e compromisso.', E'Checklist e protocolo de autoauditoria; seções 24–25') on conflict (document_key, rule_key) do update set category=excluded.category, stage=excluded.stage, priority=excluded.priority, rule_text=excluded.rule_text, operational_detail=excluded.operational_detail, source_basis=excluded.source_basis;

insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'prospect_no_reply', E'Prospect não responde', E'Checar adequação do contato; uma tentativa de encerramento só se apropriada; depois parar.', E'Cadência automática e culpa') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'prospect_rejects', E'Prospect rejeita', E'Aceitar, agradecer e suprimir contato quando pedido.', E'Tratar não como objeção a contornar') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'existing_supplier', E'Já possui fornecedor', E'Perguntar por lacuna somente com abertura; respeitar satisfação e contrato.', E'Atacar concorrente ou inventar insatisfação') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'prospect_interested', E'Prospect interessado', E'Entender critério, prioridade e participantes; avançar para passo acordado.', E'Pitch completo ou fecho precoce') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'prospect_suspicious', E'Prospect desconfiado', E'Descobrir a alegação ou risco e validar com evidência limitada.', E'Aumentar pressão ou alegar autoridade') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'discount_request', E'Cliente pede desconto', E'Diagnosticar orçamento e valor; negociar escopo ou termo com troca real.', E'Desconto imediato') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'competitor_comparison', E'Compara concorrente', E'Comparar escopo equivalente pelo critério do cliente e admitir vantagem real.', E'Alegar superioridade sem prova') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'scope_negotiation', E'Negocia escopo', E'Delimitar entregáveis, dependências, aceite, preço e mudança por escrito.', E'Trabalho ilimitado implícito') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'price_negotiation', E'Negocia preço', E'Distinguir preço, caixa, valor e risco; oferecer opções transparentes.', E'Âncora artificial ou pressão pela perda') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'aether_error', E'Aether errou', E'Reconhecer, corrigir com prazo e combinar reparação proporcional.', E'Negação, desculpa vaga ou culpabilização') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;
insert into public.aether_negotiation_scenarios (document_key, scenario_key, signal, recommended_action, avoid_action) values ('aether_ai_7_books_2026_09_28', E'do_not_sell', E'Não devemos vender', E'Explicar falta de encaixe, evidência ou capacidade e encerrar ou orientar.', E'Converter qualquer conversa em receita') on conflict (document_key, scenario_key) do update set signal=excluded.signal, recommended_action=excluded.recommended_action, avoid_action=excluded.avoid_action;

create index if not exists aether_negotiation_rules_stage_priority_idx on public.aether_negotiation_rules (stage, priority);
create index if not exists aether_negotiation_pages_document_page_idx on public.aether_negotiation_pages (document_key, page_number);

commit;

-- Verification queries: select count(*) as pages from public.aether_negotiation_pages where document_key = 'aether_ai_7_books_2026_09_28';
-- Verification queries: select count(*) as rules from public.aether_negotiation_rules where document_key = 'aether_ai_7_books_2026_09_28';
-- Verification queries: select count(*) as scenarios from public.aether_negotiation_scenarios where document_key = 'aether_ai_7_books_2026_09_28';
